plugins {
    `java-library`
}

group = "org.measly"
version = "0.1.0-SNAPSHOT"

java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
}

repositories { mavenCentral() }

dependencies {
    compileOnly(libs.djl.api)
    compileOnly(libs.slf4j.api)

    testImplementation(libs.djl.api)
    testImplementation(libs.slf4j.api)
    testImplementation(libs.logback.classic)
    testImplementation(platform(libs.junit.bom))
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
}

tasks.test {
    useJUnitPlatform()
}

// --- Codegen: IreeDataTypes from the iree-runtime-dist element_types.json ---
//
// The dist publishes this manifest inside the CMake build tree (FetchContent's
// extraction dir). Gradle cannot see CMake variables (IREE_RUNTIME_DIST_ELEMENT_TYPES
// is a CMake-only value), so we resolve the path pragmatically here instead: default
// to the known FetchContent layout, but let -PireeElementTypes=<path> override it so
// the build isn't hostage to that internal layout if it ever changes.
//
// We deliberately read straight out of native/build/_deps/... rather than asking the
// native/ CMake build to copy the file to a stable location first: changing native/ is
// out of scope for this task, and the override property already gives callers an escape
// hatch from the coupling without touching CMake.
val ireeElementTypesPath: String =
    (findProperty("ireeElementTypes") as String?)
        ?: "${projectDir}/native/build/_deps/iree_runtime_dist-src/share/iree-runtime-dist/element_types.json"

val generatedIreeSourcesDir = layout.buildDirectory.dir("generated/sources/iree")

val generateIreeDataTypes = tasks.register("generateIreeDataTypes") {
    description = "Generates IreeDataTypes.java from the iree-runtime-dist element_types.json manifest."

    val elementTypesFile = file(ireeElementTypesPath)
    val outputDir = generatedIreeSourcesDir

    inputs.property("ireeElementTypesPath", ireeElementTypesPath)
    outputs.dir(outputDir)

    doLast {
        if (!elementTypesFile.exists()) {
            throw GradleException(
                "iree-runtime-dist element_types.json not found at: $elementTypesFile\n" +
                    "This file is produced by the native CMake build (FetchContent of iree-runtime-dist).\n" +
                    "Run `./native/build.sh` first, or point at an alternate manifest with " +
                    "-PireeElementTypes=/path/to/element_types.json."
            )
        }

        // Manifest is a flat JSON object of NAME -> decimal int, e.g. {"FLOAT_32": 553648160, ...}.
        // No JSON library is on the build classpath, and the shape is simple enough that a small
        // regex scan is clearer than adding a dependency just to parse this one file.
        val json = elementTypesFile.readText()
        val entryPattern = Regex("\"([A-Za-z0-9_]+)\"\\s*:\\s*(-?\\d+)")
        val entries = LinkedHashMap<String, Long>()
        for (match in entryPattern.findAll(json)) {
            entries[match.groupValues[1]] = match.groupValues[2].toLong()
        }

        fun require(name: String): Long =
            entries[name]
                ?: throw GradleException(
                    "iree-runtime-dist element_types.json ($elementTypesFile) has no entry named " +
                        "\"$name\". Expected 24 entries per the handover doc; found ${entries.size}."
                )

        fun requireInt(name: String): Int {
            val value = require(name)
            if (value !in Int.MIN_VALUE.toLong()..Int.MAX_VALUE.toLong()) {
                throw GradleException(
                    "iree-runtime-dist element_types.json entry \"$name\" = $value does not fit in a Java int."
                )
            }
            return value.toInt()
        }

        val float32 = requireInt("FLOAT_32")
        val sint32 = requireInt("SINT_32")

        val packageDir = outputDir.get().dir("org/measly/iree/engine").asFile
        packageDir.mkdirs()
        val outFile = packageDir.resolve("IreeDataTypes.java")

        outFile.writeText(
            """
            package org.measly.iree.engine;

            import ai.djl.ndarray.types.DataType;

            /**
             * Maps DJL data types to iree_hal_element_type_t values.
             *
             * <p>GENERATED CODE - DO NOT EDIT BY HAND.
             * Generated by the {@code generateIreeDataTypes} Gradle task from
             * iree-runtime-dist's {@code element_types.json} manifest ($ireeElementTypesPath).
             * Only the types the skeleton exercises are mapped.
             */
            public final class IreeDataTypes {

                public static final int FLOAT_32 = $float32;
                public static final int SINT_32 = $sint32;

                private IreeDataTypes() {}

                public static int toIree(DataType type) {
                    switch (type) {
                        case FLOAT32:
                            return FLOAT_32;
                        case INT32:
                            return SINT_32;
                        default:
                            throw new UnsupportedOperationException(
                                    "Unsupported data type for the IREE skeleton: " + type);
                    }
                }

                public static DataType fromIree(int elementType) {
                    switch (elementType) {
                        case FLOAT_32:
                            return DataType.FLOAT32;
                        case SINT_32:
                            return DataType.INT32;
                        default:
                            throw new UnsupportedOperationException(
                                    "Unsupported IREE element type: 0x"
                                            + Integer.toHexString(elementType));
                    }
                }
            }
            """.trimIndent()
        )
    }
}

sourceSets {
    main {
        java.srcDir(generatedIreeSourcesDir)
    }
}

tasks.named("compileJava") {
    dependsOn(generateIreeDataTypes)
}

// LibUtils resolves the native library from IREE_LIBRARY_PATH before falling
// back to the classpath copy, so this variable changes WHICH .so is under test.
// Undeclared, it is invisible to the up-to-date check: point it elsewhere and
// Gradle would replay a cached pass for a run that loaded something else.
tasks.withType<Test>().configureEach {
    inputs.property(
        "ireeLibraryPath",
        providers.environmentVariable("IREE_LIBRARY_PATH").orElse("")
    )
}
