# Generated by iree-runtime-dist gen-pin.sh -- do not edit.
# Release: v3.11.0-3
#
# Paste into a consuming project and FetchContent the pinned tarball;
# the recorded SHA-256 is re-verified on every build.

set(IREE_RUNTIME_URL_default_linux-x86_64
    "https://github.com/measly-java-learning/iree-runtime-dist/releases/download/v3.11.0-3/iree-runtime-3.11.0-default-linux-x86_64.tar.gz")
set(IREE_RUNTIME_SHA256_default_linux-x86_64
    "fe23acb93e842586f296889f2d5fd11df71391af87654c06c83acd3b218c4e5e")

