# Generated by iree-runtime-dist gen-pin.sh -- do not edit.
# Release: v3.11.0-11
#
# Select a variant with the helper below; FetchContent only the pair it
# returns, so unused variants download nothing:
#   iree_runtime_dist_url("${IREE_RUNTIME_VARIANT}" "${platform}" url sha)

set(IREE_RUNTIME_DIST_default_linux-aarch64_URL
    "https://github.com/measly-java-learning/iree-runtime-dist/releases/download/v3.11.0-11/iree-runtime-3.11.0-default-linux-aarch64.tar.gz")
set(IREE_RUNTIME_DIST_default_linux-aarch64_SHA256 "739b0dee7a995071abb45df80a8803035190e9af9a2fc23afb20dc923d86e297")

set(IREE_RUNTIME_DIST_tsan_linux-aarch64_URL
    "https://github.com/measly-java-learning/iree-runtime-dist/releases/download/v3.11.0-11/iree-runtime-3.11.0-tsan-linux-aarch64.tar.gz")
set(IREE_RUNTIME_DIST_tsan_linux-aarch64_SHA256 "7ffe78b3ead1abdf25eb39f7c46293fe98bdc5192c35e50f5c53732e5e4beab9")

set(IREE_RUNTIME_DIST_default_linux-x86_64_URL
    "https://github.com/measly-java-learning/iree-runtime-dist/releases/download/v3.11.0-11/iree-runtime-3.11.0-default-linux-x86_64.tar.gz")
set(IREE_RUNTIME_DIST_default_linux-x86_64_SHA256 "adb25e93b633b56bcab75d7a6e44ff202324e2abd8455c5d3f5e02f35ce7ca5c")

set(IREE_RUNTIME_DIST_tsan_linux-x86_64_URL
    "https://github.com/measly-java-learning/iree-runtime-dist/releases/download/v3.11.0-11/iree-runtime-3.11.0-tsan-linux-x86_64.tar.gz")
set(IREE_RUNTIME_DIST_tsan_linux-x86_64_SHA256 "599aff7ac0f86625208033f2852d3abcfd7b9bc807422556b5e70d98d37692d8")

set(IREE_RUNTIME_DIST_default_windows-x86_64_URL
    "https://github.com/measly-java-learning/iree-runtime-dist/releases/download/v3.11.0-11/iree-runtime-3.11.0-default-windows-x86_64.tar.gz")
set(IREE_RUNTIME_DIST_default_windows-x86_64_SHA256 "4c7deca4fe8139d80c2c388dd9cafe2736c4708080066fc55db625ba546dc63f")

# Fixed selector -- the consumer calls this, never string-builds a variable name.
function(iree_runtime_dist_url variant platform out_url out_sha)
  set(_k "${variant}_${platform}")
  if(NOT DEFINED IREE_RUNTIME_DIST_${_k}_URL)
    message(FATAL_ERROR
      "iree-runtime-dist: no artifact for variant='${variant}' platform='${platform}'")
  endif()
  set(${out_url} "${IREE_RUNTIME_DIST_${_k}_URL}" PARENT_SCOPE)
  set(${out_sha} "${IREE_RUNTIME_DIST_${_k}_SHA256}" PARENT_SCOPE)
endfunction()
