#!/usr/bin/env bash
# Fetch the iree-runtime-dist metadata zip and publish a Gradle-friendly pin.
#
# Single source of truth: native/cmake/IreeRuntimePin.cmake (published by iree-runtime-dist
# gen-pin.sh). This script derives the release tag and repo from that file, downloads the
# iree-runtime-metadata-*.zip release asset via `gh`, normalizes it to
# third-party/iree-runtime-metadata.zip, and writes third-party/iree-runtime-metadata.properties
# for Gradle.
#
# Prerequisite: gh CLI (https://cli.github.com/) installed and authenticated.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(dirname "$here")"
pin="$root/native/cmake/IreeRuntimePin.cmake"

[ -f "$pin" ] || { echo "pin not found: $pin" >&2; exit 1; }

tag="$(sed -n 's/^# Release: \(v.*\)$/\1/p' "$pin" | head -1)"
[ -n "$tag" ] || { echo "no '# Release:' tag in $pin" >&2; exit 1; }

repo="$(grep -oE 'https://github\.com/[^/]+/[^/]+/releases/download/' "$pin" | head -1 \
  | sed -E 's#https://github\.com/([^/]+/[^/]+)/.*#\1#')"
[ -n "$repo" ] || { echo "no release download URL in $pin" >&2; exit 1; }

grep -q 'IREE_RUNTIME_DIST_default_linux-x86_64_URL' "$pin" \
  || { echo "pin lacks the default/linux-x86_64 row (pin format changed?)" >&2; exit 1; }

command -v gh >/dev/null 2>&1 \
  || { echo "gh CLI is required: https://cli.github.com/" >&2; exit 1; }

out_dir="$root/third-party"
mkdir -p "$out_dir"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

gh release download "$tag" --repo "$repo" \
  --pattern 'iree-runtime-metadata-*.zip' --dir "$tmp"

shopt -s nullglob
zip_files=("$tmp"/iree-runtime-metadata-*.zip)
[ "${#zip_files[@]}" -eq 1 ] \
  || { echo "expected exactly one metadata zip for $tag, got ${#zip_files[@]}" >&2; exit 1; }

mv -f "${zip_files[0]}" "$out_dir/iree-runtime-metadata.zip"

cat > "$out_dir/iree-runtime-metadata.properties" <<EOF
# Generated by tools/fetch-iree-metadata.sh from native/cmake/IreeRuntimePin.cmake -- do not edit.
ireeRuntimeDistTag=$tag
ireeRuntimeMetadataZip=third-party/iree-runtime-metadata.zip
EOF

echo "==> $out_dir/iree-runtime-metadata.zip ($tag)"
echo "==> $out_dir/iree-runtime-metadata.properties"
